name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3' ]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run tests
        run: |
          if [ -f ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit
          else
            echo "No tests found."
          fi

      - name: Run static analysis (phpstan)
        run: |
          if [ -f ./vendor/bin/phpstan ]; then
            ./vendor/bin/phpstan analyse src --level=max
          else
            echo "PHPStan not installed."
          fi
